[project]
name = "brawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"


dependencies = [
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "ray>=2.47.0",
    "tensordict>=0.8.3",
    "torch>=2.7.1",
]
